name: Deploy to Cloudfront

on:
  workflow_dispatch:
    inputs:
      vmRepo:
        description: Choose a source Repo to checkout.
        required: true
        type: choice
        options:
        - brainwave_builders
        - clinical_catalysts
        - cortex_coders
        - vital_visionaries

      vmRef:
        description: Enter a source Branch of the project.
        default: main              
        
run-name: ${{ github.event_name == 'workflow_dispatch' && format('CloudFront deployment of {0}:{1} to {2} ', inputs.vmRepo,  inputs.vmRef ) || '' }}        
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.vmRepo }}
    env:
       CI: false    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:  
          repository: chisquarelabs/${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.vmRef }}
          path: ${{ github.event.inputs.vmRepo }} 
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
           
      - name: Install Dependencies and Build
        run: |
            npm install 
            npm run build
        working-directory: ${{ inputs.vmRepo }}/frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: eu-west-2 

      - name: Deploy and Invalidate
        run: ./frontend/deploy-and-invalidate.sh


      - name: Cleaning workspace after job
        if: always()
        run: |
            rm -rf $GITHUB_WORKSPACE/${{ github.event.inputs.vmRepo }}
